from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from langchain_core.output_parsers import StrOutputParser

# Define the Writer Agent Prompt
WRITER_PROMPT = """
You are the WRITER AGENT, an expert educational content creator.
Your goal is to convert the provided research data into a high-quality, structured mini-course.

STRICT RULES:
- Use clear, engaging, and professional language.
- Format strictly in Markdown.
- Ensure the content is logically flowed.
- Do NOT mention "Research Data" or internal system roles.

---
### Desired Output Structure:

# 📘 [Course Title]

## 🎯 Learning Objectives
*   [Objective 1]
*   [Objective 2]
*   [Objective 3]

---

## 📖 Module 1: Core Concepts
[Detailed explanation of the fundamental concepts. Use bold text for key terms.]

## 📖 Module 2: Advanced Topics / Mechanics
[In-depth exploration of how it works, technical details, or advanced aspects.]

---

## 💡 Real-World Examples & Applications
*   **[Example 1]:** [Description]
*   **[Example 2]:** [Description]

---
*Generated by EduAgent AI*

Research Data:
{research_data}
"""

def get_writer_chain(llm=None):
    if llm is None:
        llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.7)
    
    prompt = ChatPromptTemplate.from_template(WRITER_PROMPT)
    chain = prompt | llm | StrOutputParser()
    return chain
